### PR TITLE
feat: inspect element immediately at mouse point while press hotkey

### LINKED ISSUE #105: visual indicator of dev-inspector is "active"
First of all thanks for such an amazing project, i do have a suggestion that there should be a UI indicator or sorts, since currently, when i press the hotkey combination, if i don't move the mouse, i do not know that the inspector is active.

### PR DESCRIPTION
**Pull request by zthxxx**
for resolve #105 #106

cc: @murugaratham

### CODE REVIEW

**Comment by zthxxx** [comment]
@murugaratham I'll merge it if you confirm it looks good

**Comment by murugaratham** [comment]
Just a small thing, but it seems to only happen at src/layouts/index.tsx, but for the considerations of trying not to alter `Overlay.js`. I think it looks good to me

Screenshot 2021-11-02 at 5 05 52 PM

**Comment by zthxxx** [comment]
> Just a small thing, but it seems to only happen at src/layouts/index.tsx, but for the considerations of trying not to alter `Overlay.js`. I think it looks good to me

cause by dom order

image

**Comment by murugaratham** [comment]
I think it's a very minor issue, maybe a .nvmrc would do more good 😀

**Comment by murugaratham** [comment]
> > Just a small thing, but it seems to only happen at src/layouts/index.tsx, but for the considerations of trying not to alter `Overlay.js`. I think it looks good to me
> 
> 
> 
> cause by dom order
> 
> 
> 
> image
> 
> 
> 
> 
> 
> 

I just noticed that it can be seen "reproduced" at the start of the gif https://react-dev-inspector.zthxxx.me/images/inspect.gif

**Comment by zthxxx** [comment]
@murugaratham  updated

image

**Comment by zthxxx** [comment]
release in react-dev-inspector@1.7.1

**Comment by zthxxx** [comment]
> I think it's a very minor issue, maybe a .nvmrc would do more good 😀

for development, this project works with node >= v12 and npm >= v7, but in node v12/v14 now default version of npm is still v6

**Pull request merged**
