### PR TITLE
docs: correct nextjs integration error handle

### PR DESCRIPTION
**Pull request by tjx666**
- https://nextjs.org/docs/pages/building-your-application/configuring/custom-server

image

### CODE REVIEW

**Comment by zthxxx** [comment]
Ohhhh, they changed it.

**Comment by zthxxx** [comment]
~~Please enable the `Allow edits from maintainers` option for this PR, which make me could update related docs and merge them into your branch.~~


Never mind, you already enabled it. 

The error I got, `error: Authentication error: Authentication required: You must have push access to verify locks`, was caused by git-lfs/git-lfs#2291. 

It’s resolved now.

**Comment by tjx666** [comment]
@zthxxx 请教一下你是怎么做到在我的 pr 上提交代码的？我有个仓库也收到 pr，我想在他 pr 的分支改点东西

**Comment by zthxxx** [comment]
@tjx666  当对方开启 `Allow edits from maintainers` option 的时候，你就有对应分支 push 权限

配合 GitHub Cli `gh pr checkout 176` 就能方便的拉到本地

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Pull request merged**
